In [142]:
import pandas as pd
import sklearn as sns
import math
import random
from operator import itemgetter
import random

In [108]:
movie = pd.read_csv("ratings.csv")
movie = movie.drop(columns = ['timestamp'])
# movie = movie.drop(columns = ['timestamp'])[["userId","movieId"]]
# movie[["userId","movieId"]]
movie.head()
# # print(movie.index)
# table = pd.pivot_table(movie,values = "rating",index = ['userId'],columns = ['movieId'])
# # list(table.index)
# table.head()
# print(list(movie.items()))
# for u,i in movie.items():
#     print([u,i])

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
def DataPrep(raw_data):
    Data = {}
    for index,row in raw_data.iterrows():
        if int(row['userId']) not in Data:
            Data[int(row['userId'])] = {}
        if(row['rating']>=3):
            Data[int(row['userId'])][int(row['movieId'])] = row['rating']
    return Data

In [114]:
data = DataPrep(movie)

In [115]:
def CompMatrix(train):
    C = {}
    N = {}
    for users,items in train.items():
#         print(users,items)
        for i in items:
            if i not in N:
                N[i] = 1
            else:
                N[i] += 1
            for j in items:
                if i==j:
                    continue
                if i not in C:
                    C[i] = {j:1}
                else:
                    if j not in C[i]:
                        C[i][j] = 1
                    else:
                        C[i][j] += 1
    return C,N

In [116]:
C,N = CompMatrix(data)

In [117]:
def CalItemSimilarity(C,N):
    W = {}
    for i, related_items in C.items():
        for j,Cij in related_items.items():
            temp = Cij/math.sqrt(N[i]*N[j])
            if i not in W:
                W[i] = {j:temp}
            if j not in W[i]:
                W[i][j] = temp
    return W

In [118]:
Weight = CalItemSimilarity(C,N)

In [135]:
def splitYvalue(data, seed,m,k):
    train_set = {}
    y_set = {}
    random.seed(seed)
    for user in data:
        y_set[user] = {}
        train_set[user] = {}
        for movie in data[user]:
            if random.randint(0,m)<k:
                y_set[user][movie] = data[user][movie]
            else:
                train_set[user][movie] = data[user][movie]
#         train = movies[:int(0.8*len(movies))]
#         y = movies[int(0.8*len(movies)):]
    #print('Data preparation finished')
    return train_set, y_set

In [150]:
train, y_set = splitYvalue(data,2,10,2.5)
print(len(train[1]),len(y_set[1]))

160 66

In [123]:
def Recommendation(train,user_id,W,k):
    rank = {}
    ru = train[user_id] #get the set of movies watched by user_id
    for i in ru:
        #iterate all movies j that user_id havent watched yet
        for j,wij in sorted(W[i].items(),key = itemgetter(1),reverse = True)[0:k]:
            if j in ru:
                continue
            #get the rating of movie i rated by user_id
            pi = ru[i]
            if j in rank:
                rank[j] += pi*wij
            else:
                rank[j] = pi*wij
    return rank

In [155]:
rank = sorted(Recommendation(train,4,Weight,5).items(),key = itemgetter(1),reverse = True)
maximal = rank[0][1]
y = y_set[4]
recommand = {}
for i in rank:
    recommand[i[0]] = round(i[1]*5/maximal,1)

In [156]:
def ResultPrep(recommand,y):
    res = []
    for movie in y:
        if movie in recommand:
            res.append([y[movie],recommand[movie]])
    return np.array(res)

In [157]:
result = ResultPrep(recommand,y)
result

KeyError: 58

In [125]:
#evaluation:
def rmse(result):
    return np.sqrt(np.mean((result[:, 0]-result[:, 1])**2))